### ISSUE TITLE
Web interface cannot connect to server

### ISSUE THREAD

**Issue by keithzg** [OhMyGuus/BetterCrewLink-server#20]
For some reason, when I run my own server instance, users of the Windows and Linux app can connect just fine, but users of the web app cannot. With the same people and even the same game code, the default server works just fine!

**Comment by OhMyGuus** [comment]
Assuming you are running it locally, the mobile app version requires ssl to work, the web version requires ssl as well if u use it on https://web.bettercrewl.ink/. U can however use http://web.bettercrewl.ink

**Comment by keithzg** [comment]
Ohh, interesting! A tad unfortunate but as long as it works. I can easily either actually get a valid cert via LetsEncrypt or such, or just get the few web users to use the non-SSL protocol prefix.
